version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "5001:5000"   # Change host port to 5001
    environment:
      - NODE_ENV=production
