version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=vinuthnavenigalla
      - DATABASE_PASSWORD=vinu2907
      - DATABASE_NAME=postgres
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5001:5000" 
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=vinuthnavenigalla
      - POSTGRES_PASSWORD=vinu2907
    ports:
      - "5432:5432"  # Map PostgreSQL port to the host
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge